### ISSUE TITLE
Remove a node ?

### ISSUE THREAD

**Issue by ManUtopiK** [prosekit/prosekit#398]
I found a way to remove a mark here : https://github.com/ocavue/prosekit/blob/master/packages/core/src/commands/remove-mark.ts
But how to remove a node ?

**Comment by ocavue** [comment]
There are some APIs in ProseMirror to delete some nodes from the document, like [`tr.delete()`](https://prosemirror.net/docs/ref/#transform.Transform.delete) and [`tr.deleteRange()`](https://prosemirror.net/docs/ref/#transform.Transform.deleteRange). I could provide some handier APIs on the ProseKit side, though. Could you elaborate on what kind of "remove" you want?"

**Comment by ManUtopiK** [comment]
I'd just wondered if there was an utility like [`insertNode`](https://github.com/ocavue/prosekit/blob/master/packages/core/src/commands/insert-node.ts#L15C10-L15C20) to remove a node.
I use this to doing the job :
```js
const selection = editor.value.state.selection
// Create a transaction that removes the content covered by the selection
const tr = editor.value.state.tr.delete(selection.from, selection.to)
// Apply the transaction to the editor
editor.value.view.dispatch(tr)
```
