### ISSUE TITLE
Notes for Nuxt

### ISSUE THREAD

**Issue by ManUtopiK** [prosekit/prosekit#519]
Not really an issue. Just notes.
Here a [working demo](https://stackblitz.com/edit/stackblitz-starters-zkgyrw).

## Add typescript
We need to add typescript in dev dependencies otherwise Nuxt complains about `VueNodeViewProps`.
Don't know why, I thought that Nuxt already embed typescript.

![image](https://github.com/ocavue/prosekit/assets/188172/0bf5e81d-74a6-4d28-b12a-a24cfd534577)

    pnpm add -D typescript

## Set client only

As Nuxt build the app in SSR, we need to rename `editor.vue` to `editor.client.vue`, or wrap the `ProseKit` component with the `<client-only>`. Otherwise, the html of prosekit is provided at build time and components like inline menu or block handle doesn't trigger after hydration.

## Add button reset

Somewhere your style, add :
```css
button {
  border: none;
}
```

**Comment by ManUtopiK** [comment]
In fact there is an issue. 
From the demo bellow, write something in the editor and open the console to see an error :

![image](https://github.com/ocavue/prosekit/assets/188172/37571432-e538-4610-917a-5ea4200ab80f)

This error didn't happen with `0.6.10`. I've take a look but don't understand where it comes from.

**Comment by ocavue** [comment]
> We need to add typescript in dev dependencies otherwise Nuxt complains about `VueNodeViewProps`.

I'm not a Nuxt expert, but I think adding `typescript` in dev dependencies is a good idea in general for any TypeScript projects. Explicit is better than implicit.

---

> The html of prosekit is provided at build time and components like inline menu or block handle doesn't trigger after hydration.

In general, for a heavy component that depends on browser APIs like rich-text editor, it's a good idea to skip server-side rendering for it.

However, I don't understand why only the inline menu and block handle are broken. It's interesting and I will look into it. 

---

Somewhere your style, add:

```
button {
  border: none;
}
```

I don't want to alter the global styles, but I can add `border-transparent` to every needed component. 

---

> `Uncaught (in promise) Error: Editor is already mounted`

I will investigate it.

**Comment by ManUtopiK** [comment]
My `onMounted` hack is not ideal, all commands no longer work.
Still with Nuxt, I've rollback to 0.6.10 and confirm that the `Error: Editor is already mounted` doesn't occur.

**Comment by ocavue** [comment]
prosekit@0.9.7 brings various improvements for SSR. Please check it out. You can also find a Nuxt example in https://github.com/prosekit/examples. 

I'll close this issue for now. Let me know if see any other Nuxt issues.
