### ISSUE TITLE
Empty selection should not trigger inline menu

### ISSUE THREAD

**Issue by egoist** [prosekit/prosekit#689]
The inline menu is shown when I'm selecting an empty line

https://github.com/user-attachments/assets/f2b6cc17-a42c-4431-aef3-6a9e48bfdf9d

**Comment by ocavue** [comment]
And the `Bold`, `Italic` buttons should not be highlighted if multiple empty paragraphs are selected. I will fix both of them.

**Comment by ocavue** [comment]
Fixed in prosekit@0.9.10. Thanks for reporting.
