### ISSUE TITLE
How should we understand `Facet` and `Extension`?

### ISSUE THREAD

**Issue by shlroland** [prosekit/prosekit#693]
In simple terms, they allow us to build different parts of an editor in a flexible manner. Extension has already incorporated the relevant context type information of `Prosemirror`, while some APIs of `Facet` have not been made available for use.

I would like to bind some additional contexts (unrelated to `Prosemirror`) to the Editor in a similar way. For instance, if I use a markdown parser like `remark` and want to register functions for mapping `ast` in a distributed manner across files, similar to what [milkdown](https://github.com/Milkdown/milkdown) does, it seems to be a challenging task?

**Comment by ocavue** [comment]
Facet is an internal concept that I want to hide from users, that's why it's not exported as public API.

Binding additional contexts (unrelated to Prosemirror) exceeds the scope of ProseKit. You can easily do that yourself by exporting related APIs from the same file. Here is an example:


```
// src/editor.ts
import { defineHeading, astHeading } from './extensions/heading'
import { defineCodeBlock, astCodeBlock } from './extensions/code-block'

const prosekitExtension = union([defineHeading(), defineCodeBlock(), /*...*/])
const remarkAst = mergeAst([astHeading, astCodeBlock, /*...*/])
```
