### ISSUE TITLE
Example for file dropping

### ISSUE THREAD

**Issue by egoist** [prosekit/prosekit#791]
A common use case is dropping images/files to upload and insert into the editor, would be great to have an example or even better an extension for this

**Comment by saivan** [comment]
I don't seem to be able to drop images or files into your online demos either, seems like something to add

**Comment by ocavue** [comment]
I will implement this feature with some examples.

**Comment by ocavue** [comment]
Please check https://prosekit.dev/extensions/file for some examples and explanation.
